# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

san_timediscrete_c <- function(C_init, p_S, p_0, p_R, p_A, p_N, p_D, steps) {
    .Call(`_SANjar_san_timediscrete_c`, C_init, p_S, p_0, p_R, p_A, p_N, p_D, steps)
}

